name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Backend install and build
        working-directory: backend
        run: |
          npm install
          npm run build
      - name: Frontend install and build
        working-directory: app
        run: |
          npm install
          npm run build
